branches:
  only:
  - master
language: objective-c
before_install:
  - brew update
  - brew install mongo
  - ln -sfv /usr/local/opt/mongodb/*.plist ~/Library/LaunchAgents
  - launchctl load ~/Library/LaunchAgents/homebrew.mxcl.mongodb.plist
  - brew outdated node || brew upgrade node
before_script:
  - npm install -g grunt-cli
  - npm install -g gulp
  - npm install
script:
  - grunt build
  - ./deploy.sh
